### ISSUE TITLE
Importing DICOM-RT Dose file causes crash if no matching Plan is found

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#105]
When associating DICOM-RT Dose files, the current code assumes there is a DICOM-RT Plan file with matching `PatientID` and `StudyInstanceUID`, potentially causing a `KeyError`.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\dcutright\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\models\dicom_tree_builder.py", line 478, in run
    self.do_association()
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\models\dicom_tree_builder.py", line 580, in do_association
    for plan_file_set in self.plan_file_sets[mrn][study_uid].values():
KeyError: '<omitted>'
```

**Comment by cutright** [comment]
Fixed in 0.8.9
