### ISSUE TITLE
Empty ROI slice crashes DTH calculation

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#113]
Seems to be a rare error.  I came across a structure that contained an empty contour, causing `is_point_inside_roi` to crash because `points_to_shapely_polygon` returned `None`.
https://github.com/cutright/DVH-Analytics/blob/517b85f4b6e3b64a85b253ada03cf52fda95157f/dvha/tools/roi_geometry.py#L108-L126

```
ERROR: Unhandled exception: Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/main.py", line 1221, in Run
    run_old(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/models/import_dicom.py", line 1490, in import_target
    StudyImporter(*parameters)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/models/import_dicom.py", line 1193, in __init__
    self.run()
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/models/import_dicom.py", line 1322, in run
    db_update.min_distances, tv)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/models/import_dicom.py", line 1370, in post_import_calc
    func(uid, roi_name, pre_calc=pre_calc)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/db/update.py", line 119, in min_distances
    is_inside = [[1, -1][roi_geom.is_point_inside_roi(point, treatment_volume_roi)] for point in oar_coordinates]
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/db/update.py", line 119, in <listcomp>
    is_inside = [[1, -1][roi_geom.is_point_inside_roi(point, treatment_volume_roi)] for point in oar_coordinates]
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/tools/roi_geometry.py", line 125, in is_point_inside_roi
    return shapely_point.within(shapely_roi)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv/lib/python3.6/site-packages/shapely/geometry/base.py", line 779, in within
    return bool(self.impl['within'](self, other))
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv/lib/python3.6/site-packages/shapely/predicates.py", line 13, in __call__
    self._validate(other, stop_prepared=True)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv/lib/python3.6/site-packages/shapely/topology.py", line 18, in _validate
    raise ValueError("Null geometry supports no operations")
ValueError: Null geometry supports no operations
```

**Comment by cutright** [comment]
Although the above commit resolved the crash, the calculation is incorrect. `is_point_inside_roi` is always reporting `False`.  This was confirmed by trying to reproduce the plots here: https://github.com/cutright/DVH-Analytics/issues/111
