### ISSUE TITLE
Database Administrator fails to delete by StudyInstanceUID

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#135]
```
ERROR: Unhandled exception: Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/models/database_editor.py", line 365, in on_delete_study
    self.change_or_delete_dlg(DeletePatientDialog)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/models/database_editor.py", line 371, in change_or_delete_dlg
    mrn=selected_data[0][0], study_instance_uid=selected_data[0][1]
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/dialogs/database.py", line 452, in __init__
    study_instance_uid=study_instance_uid,
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/dialogs/database.py", line 264, in __init__
    self.run()
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/dialogs/database.py", line 337, in run
    self.action()
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/dialogs/database.py", line 460, in action
    **{self.sql_column: value}
TypeError: get_dicom_file_paths() got an unexpected keyword argument 'study_instance_uid'
```
Rookie mistake, incorrect kwarg passed.

**Comment by cutright** [comment]
fixed in v0.9.3
