### ISSUE TITLE
DVHA Crashes due to recent FractionGroupSequence fix

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#137]
Please upgrade to `v0.9.3.post1` if you are on `v0.9.3`.  Will post a fix for this today.

```
(venv-production) C:\Users\dcutright\PycharmProjects\DVH-Analytics>python dvha_app.py
ERROR: Unhandled exception: Traceback (most recent call last):
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\main.py", line 1800, in Run
    run_old(*args, **kwargs)
  File "C:\Users\dcutright\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\models\dicom_tree_builder.py", line 963, in do_parse
    self.parser(*parameters)
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\models\dicom_tree_builder.py", line 980, in parser
    pre_import_data = DICOM_Parser(**init_params).pre_import_data
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\db\dicom_parser.py", line 144, in __init__
    self.__initialize_rx_beam_and_ref_beam_data()
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\db\dicom_parser.py", line 207, in __initialize_rx_beam_and_ref_beam_data
    self.study_instance_uid_to_be_imported,
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\db\dicom_parser.py", line 2580, in __init__
    self.dose_ref_index = self.get_dose_ref_seq_index()
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\db\dicom_parser.py", line 2598, in get_dose_ref_seq_index
    if dose_ref.DoseReferenceNumber == self.fx_grp_number:
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\db\dicom_parser.py", line 2658, in fx_grp_number
    if self.fx_grp_data is None:
AttributeError: 'RxParser' object has no attribute 'fx_grp_data'
```

**Comment by cutright** [comment]
Fix with:

Changes to dicomp_parser.py:
https://github.com/cutright/DVH-Analytics/commit/3e5434be8427287bd6c9cdd7ef28ed0bc1170c2a#diff-af047a91b7fe90d42a646241efdeb70a40a0ef4d883f4f291e77f664a68c60a7
