### ISSUE TITLE
Checking for Edge Backend prevents User Settings from opening if Edge is unavailable

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#144]
```
2021-02-12 12:39:48,196 - dvha - ERROR - Unhandled exception: Traceback (most recent call last):
  File "dvha\main.py", line 1528, in on_pref
  File "dvha\dialogs\main.py", line 966, in __init__
  File "dvha\tools\utilities.py", line 1628, in is_edge_backend_available
wx._core.wxAssertionError: C++ assertion "m_handle == 0" failed at ..\..\src\common\dynlib.cpp(67) in wxDynamicLibrary::Load(): Library already loaded.
```

**Comment by cutright** [comment]
resolved in 0.9.5 branch
