### ISSUE TITLE
Image Export module crashes with wxPython 4.1.1

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#146]
This used to just be a warning, with wxPython 4.1.1 it's an error.

```
Traceback (most recent call last):
  File "/Users/owls/PycharmProjects/DVH-Analytics/dvha/main.py", line 1562, in on_export_figure
    self.export_figure = ExportFigure(self)
  File "/Users/owls/PycharmProjects/DVH-Analytics/dvha/dialogs/export.py", line 391, in __init__
    self.__do_layout()
  File "/Users/owls/PycharmProjects/DVH-Analytics/dvha/dialogs/export.py", line 529, in __do_layout
    self.button["Export"], 1, wx.EXPAND | wx.ALIGN_CENTER | wx.ALL, 5
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/sizer.cpp(2184) in DoInsert(): Vertical alignment flags are ignored with wxEXPAND

```

**Comment by cutright** [comment]
Fixed in v0.9.6
