### ISSUE TITLE
Building wheel for wxPython (setup.py) ... error

### ISSUE THREAD

**Issue by sama2689** [cutright/DVH-Analytics#165]
I'm trying to install on Ubuntu with pip and am getting the error in the title. My wxpython version is 4.0.4. The full error message is quite verbose so I will post it below, I think it has something to do with wxpython and gtk but I am not quite able to pin down what the issue seems to be.

```
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/anaconda3/envs/myenvname/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pq8s2t4v/wxpython_3838d3625b784489a54d38c0515a1ffc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pq8s2t4v/wxpython_3838d3625b784489a54d38c0515a1ffc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-i66w33iq
       cwd: /tmp/pip-install-pq8s2t4v/wxpython_3838d3625b784489a54d38c0515a1ffc/
  Complete output (140 lines):
  running bdist_wheel
  running build
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.
  
  "/home/user/anaconda3/envs/myenvname/bin/python" -u build.py build
  Will build using: "/home/user/anaconda3/envs/myenvname/bin/python"
  3.7.10 (default, Feb 26 2021, 18:47:35)
  [GCC 7.3.0]
  Python's architecture is 64bit
  cfg.VERSION: 4.1.1
  
  Running command: build
  Running command: build_wx
  wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
  Configure options: ['--enable-unicode', '--with-gtk=3', '--enable-sound', '--enable-graphics_ctx', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--enable-autoidman', '--with-sdl']
  /tmp/pip-install-pq8s2t4v/wxpython_3838d3625b784489a54d38c0515a1ffc/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --enable-sound --enable-graphics_ctx --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --enable-autoidman --with-sdl
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking for toolkit... gtk
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether we are using the Intel C compiler... no
  checking how to run the C preprocessor... gcc -E
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for egrep... /usr/bin/grep -E
  checking whether gcc needs -traditional... no
  checking for g++... g++
  checking whether we are using the GNU C++ compiler... yes
  checking whether g++ accepts -g... yes
  checking whether we are using the Intel C++ compiler... no
  checking whether we are using the Sun C++ compiler... no
  checking for ar... ar
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for langinfo.h... yes
  checking for wchar.h... yes
  checking for sys/select.h... yes
  checking for cxxabi.h... yes
  checking for an ANSI C-conforming const... yes
  checking for inline... inline
  checking size of short... 2
  checking size of void *... 8
  checking size of int... 4
  checking size of long... 8
  checking size of size_t... 8
  checking size of long long... 8
  checking size of wchar_t... 4
  checking for va_copy... yes
  checking for _FILE_OFFSET_BITS value needed for large files... 64
  checking if large file support is available... yes
  checking for _LARGEFILE_SOURCE value needed for large files... no
  checking whether byte ordering is bigendian... no
  checking for std::wstring in <string>... yes
  checking for std::istream... yes
  checking for std::ostream... yes
  checking for type_traits... yes
  checking for __sync_fetch_and_add and __sync_sub_and_fetch builtins... yes
  checking for libraries directories... /usr/lib/x86_64-linux-gnu /usr/lib
  checking for cos... no
  checking for floor... no
  checking if floating point functions link without -lm... no
  checking for sin... yes
  checking for ceil... yes
  checking if floating point functions link with -lm... yes
  checking for strtoull... yes
  checking for pkg-config... /usr/bin/pkg-config
  checking pkg-config is at least version 0.9.0... yes
  configure: WARNING: Defaulting to the builtin regex library for Unicode build.
  checking for zlib.h >= 1.1.4... yes
  checking for zlib.h... (cached) yes
  checking for deflate in -lz... yes
  checking for png.h > 0.90... yes
  checking for png.h... (cached) yes
  checking for png_sig_cmp in -lpng... yes
  checking for jpeglib.h... no
  configure: WARNING: system jpeg library not found, will use built-in instead
  checking whether jpeglib.h file exists... yes
  checking lzma.h usability... no
  checking lzma.h presence... no
  checking for lzma.h... no
  checking for jbg_dec_init in -ljbig... no
  checking for LIBTIFF... not found via pkg-config
  checking for tiffio.h... no
  configure: WARNING: system tiff library not found, will use built-in instead
  checking whether tiff.h file exists... yes
  checking for expat.h... no
  configure: WARNING: system expat library not found, will use built-in instead
  checking whether expat.h file exists... yes
  checking for gcc option to accept ISO C99... none needed
  checking for GTK+ version...
  checking for pkg-config... (cached) /usr/bin/pkg-config
  checking pkg-config is at least version 0.16... yes
  checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gtk+-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gtk+-3.0' found
  no
  *** Could not run GTK+ test program, checking why...
  *** The test program failed to compile or link. See the file config.log for the
  *** exact error that occurred. This usually means GTK+ is incorrectly installed.
  configure: error:
  The development files for GTK+ were not found. For GTK+ 2, please
  ensure that pkg-config is in the path and that gtk+-2.0.pc is
  installed. For GTK+ 1.2 please check that gtk-config is in the path,
  and that the version is 1.2.3 or above. Also check that the
  libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
  --libs' are in the LD_LIBRARY_PATH or equivalent.
  
  Error running configure
  ERROR: failed building wxWidgets
  Traceback (most recent call last):
    File "build.py", line 1510, in cmd_build_wx
      wxbuild.main(wxDir(), build_options)
    File "/tmp/pip-install-pq8s2t4v/wxpython_3838d3625b784489a54d38c0515a1ffc/buildtools/build_wxwidgets.py", line 373, in main
      "Error running configure")
    File "/tmp/pip-install-pq8s2t4v/wxpython_3838d3625b784489a54d38c0515a1ffc/buildtools/build_wxwidgets.py", line 85, in exitIfError
      raise builder.BuildError(msg)
  buildtools.builder.BuildError: Error running configure
  Finished command: build_wx (0m2.719s)
  Finished command: build (0m2.719s)
  Command '"/home/user/anaconda3/envs/myenvname/bin/python" -u build.py build' failed with exit code 1.
  ----------------------------------------
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
```

**Comment by cutright** [comment]
You probably need to build wxpython from source.  I recently documented my experience installing DVHA on Ubuntu here: https://github.com/cutright/DVH-Analytics/issues/157

**Comment by cutright** [comment]
Specifically this comment: https://github.com/cutright/DVH-Analytics/issues/157#issuecomment-828924940

**Comment by sama2689** [comment]
Hm, that advice has changed the error I am getting but it seems I am still getting a build wheel error. I have run
```
sudo apt install libgtk-3-dev
sudo apt-get install python-wxgtk3.0​
```

The former ran fine, the latter gave the message

```
E: Unable to locate package python-wxgtk3.0​
E: Couldn't find any package by glob 'python-wxgtk3.0​'
E: Couldn't find any package by regex 'python-wxgtk3.0​' 
```
Nevertheless I proceeded with 

`sudo apt install libwebkit2gtk-4.0-dev`

and then installed+built wxpython with `conda install -c conda-forge wxpython`

Lastly, ran `pip install dvha`, but this still returns an error. The first error message is so verbose that it overflows the entire terminal, so I can't quite read it in full. But essentially it says   Running setup.py clean for wxPython
```
Failed to build wxPython
Installing collected packages: wxPython, pypubsub, psycopg2-binary, bokeh, dvha
  Attempting uninstall: wxPython
    Found existing installation: wxPython 4.0.4
    Uninstalling wxPython-4.0.4:
      Successfully uninstalled wxPython-4.0.4
    Running setup.py install for wxPython ... error
```
Does condaforge installation not work for building wxpython with?

**Comment by cutright** [comment]
I'm not 100% sure. To be honest, I stay away from Anaconda because it is so bloated... it installs all kinds of stuff I don't want.

But it looks like [conda is stuck on wxpython==4.0.4 as the latest](https://anaconda.org/anaconda/wxpython), so you'll have to install from source or pip because DVHA requires `>=4.1.1`.

I'm also still suspect of the `python-wxgtk3.0​` error.

Often the last line or error is the most useful.  You could also copy the error into a text document and attach it to a comment here.

**Comment by cutright** [comment]
Alternatively, you could try installing `dvha==0.9.2.post2` which was the last version before going to `wxpython 4.1.1`.  Lots of issues have been fixed since that DVHA version, but worth finding out if it at least installs for you.

**Comment by sama2689** [comment]
hm, manually installing wxpython via  `pip install wxpython==4.1.1` didn't quite work for me. Last line of error below

`ERROR: Command errored out with exit status 1: /home/user/anaconda3/envs/myenv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hs66doa9/wxpython_fb9ddf8a41b44960b7b9a39c950ffef1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hs66doa9/wxpython_fb9ddf8a41b44960b7b9a39c950ffef1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-y57lm4t2/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/anaconda3/envs/myenv/include/python3.7m/wxpython Check the logs for full command output.`


Does this version of wxPython work on python 3.7?

Installing dvha 0.9.1 works just fine

**Comment by cutright** [comment]
Certainly no issues with python 3.7 on macOS or Windows.  I don't recall which version of python I had on my Ubuntu VM, but I'm more inclined to think it is an issue with the non-python dependencies of wxpython and your environment.  This process can be painful if any step fails or you go out of order.

I would focus on just getting the latest version of wxpython installed and working.  Based on one of our other Linux users: 
https://github.com/cutright/DVH-Analytics/issues/157#issuecomment-829251444

> In my experience, python wheels or Conda packages never run DVH-Analytics on Linux, I have always had to build wxpython from source, then it links to my current OS libraries. If you update your OS libraries, you might have to rebuild wxpython again.

**Comment by sama2689** [comment]
Gotcha, I think you're write that wxpython is the root problem. That being said I've not really been able to figure out how to build wxpython from source unfortunately and the process to do so seems incredibly daunting at my skill level. I suppose I will just stick to 0.9.1 for now!

**Comment by cutright** [comment]
Just be sure to take note of the changes since then, in case you come across some issues: https://github.com/cutright/DVH-Analytics/blob/master/CHANGELOG.md

If you need to upgrade wxpython, I've found Robin and the wxpython community to be very helpful: https://discuss.wxpython.org/

**Comment by sama2689** [comment]
Found somewhat of a simple workaround to this, I used python 3.8 and everything works without issue
