### ISSUE TITLE
"Reimport From DICOM" fails in Database Adminstrator

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#19]
The Database Administrator has an option to reimport data into the SQL database from the original DICOM files.  Currently, this will crash and if you selected to delete data in the database, that data will be deleted.  The original DICOM files will not be deleted.

Current work-around is to use the usual DICOM Import feature. Fix coming in release of v0.6.4

```
Traceback (most recent call last):
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\models\database_editor.py", line 238, in on_reimport
    ReimportDialog()
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\dialogs\database.py", line 453, in __init__
    self.run()
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\dialogs\database.py", line 508, in run
    self.action()
  File "C:\Users\dcutright\PycharmProjects\DVH-Analytics\dvha\dialogs\database.py", line 573, in action
    ImportDicomFrame(inbox=INBOX_DIR)
TypeError: __init__() missing 2 required positional arguments: 'roi_map' and 'options'
```

**Comment by cutright** [comment]
Fixed in 0.6.4 here: f65e1dd
