### ISSUE TITLE
Cannot add a new Physician to ROI Map

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#75]
I'm not sure when this bug was introduced, but at least after TG-263 implementation.  I'll post a new release by end of the day tomorrow.  The following occurs when trying to add a new physician in the import screen or in the ROI map module.

```
(venv) Ninjas-MacBook-Pro:DVH-Analytics ninja$ python dvha_app.py
<class 'dict'> {'Anatomic Group': ['Abdomen']}
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/models/roi_map.py", line 485, in add_physician
    dlg = AddPhysician(self.roi_map)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/dialogs/roi_map.py", line 57, in __init__
    self.run()
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/dialogs/roi_map.py", line 112, in run
    self.action()
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/dialogs/roi_map.py", line 101, in action
    dlg = TG263Dialog(physician, self.roi_map)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/dialogs/roi_map.py", line 144, in __init__
    self.run()
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/dialogs/roi_map.py", line 193, in run
    self.map_file_path = self.generator(map_file_name, body_sites=self.checked_values)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/tools/roi_map_generator.py", line 40, in __call__
    data = self.tg_263 if data_filter is None else self.get_filtered_data(data_filter)
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/tools/roi_map_generator.py", line 84, in get_filtered_data
    if data_filter[key].lower() == 'all':
AttributeError: 'list' object has no attribute 'lower'
```

**Comment by cutright** [comment]
fixed in `v0.7.9`
