### ISSUE TITLE
wxPython==4.1.0 crashes DVHA

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#77]
One of my DVH DICOM Editor users found an [issue](https://github.com/cutright/DVHA-DICOM-Editor/issues/8) with `wxpython==4.1.0`.  You'll get the following error:

```
(venv2) Ninjas-MacBook-Pro:DVH-Analytics ninja$ python dvha_app.py
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/main.py", line 1086, in OnInit
    self.frame = DVHAMainFrame(None, wx.ID_ANY, "")
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/main.py", line 103, in __init__
    self.__do_layout()
  File "/Users/ninja/PycharmProjects/DVH-Analytics/dvha/main.py", line 349, in __do_layout
    sizer_query_exec_buttons.Add(self.button_query_execute, 1, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.ALIGN_CENTER, 10)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/sizer.cpp(2114) in DoInsert(): Vertical alignment flags are ignored with wxEXPAND
OnInit returned false, exiting...
```

**Comment by cutright** [comment]
Pushed v0.7.9.post1 to PyPI and master branch with:
https://github.com/cutright/DVH-Analytics/blob/fba3903fc4f081a8ecf8a50b8cc29ba93b94d83c/requirements.txt#L2
