### ISSUE TITLE
Pandas 1.0.3 breaks Regressors and Bokeh 1.4.0

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#80]
I'm guessing all 1.0 versions of Pandas breaks regressors and bokeh 1.4.0, but certainly 1.0.3 does.  Solution: downgrade to pandas 0.25.3.

I will update the DVHA requirements.txt

```
(venv2) Ninjas-MacBook-Pro:DVH-Analytics ninja$ dvha
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/bokeh-1.4.0-py3.6.egg/bokeh/util/dependencies.py", line 63, in import_optional
    return import_module(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/ops.py", line 15, in <module>
    import pandas.core.common as com
AttributeError: module 'pandas' has no attribute 'core'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/bokeh-1.4.0-py3.6.egg/bokeh/util/dependencies.py", line 63, in import_optional
    return import_module(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/ops.py", line 15, in <module>
    import pandas.core.common as com
AttributeError: module 'pandas' has no attribute 'core'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/bokeh-1.4.0-py3.6.egg/bokeh/util/dependencies.py", line 63, in import_optional
    return import_module(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/ops.py", line 15, in <module>
    import pandas.core.common as com
AttributeError: module 'pandas' has no attribute 'core'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/bokeh-1.4.0-py3.6.egg/bokeh/util/dependencies.py", line 63, in import_optional
    return import_module(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/ops.py", line 15, in <module>
    import pandas.core.common as com
AttributeError: module 'pandas' has no attribute 'core'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/bokeh-1.4.0-py3.6.egg/bokeh/util/dependencies.py", line 63, in import_optional
    return import_module(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/ops.py", line 15, in <module>
    import pandas.core.common as com
AttributeError: module 'pandas' has no attribute 'core'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/bokeh-1.4.0-py3.6.egg/bokeh/util/dependencies.py", line 63, in import_optional
    return import_module(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/ops.py", line 15, in <module>
    import pandas.core.common as com
AttributeError: module 'pandas' has no attribute 'core'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/bokeh-1.4.0-py3.6.egg/bokeh/util/dependencies.py", line 63, in import_optional
    return import_module(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/ops.py", line 15, in <module>
    import pandas.core.common as com
AttributeError: module 'pandas' has no attribute 'core'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/bokeh-1.4.0-py3.6.egg/bokeh/util/dependencies.py", line 63, in import_optional
    return import_module(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/ops.py", line 15, in <module>
    import pandas.core.common as com
AttributeError: module 'pandas' has no attribute 'core'
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/bin/dvha", line 11, in <module>
    load_entry_point('dvha==0.8.1', 'console_scripts', 'dvha')()
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 489, in load_entry_point
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 2793, in load_entry_point
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 2411, in load
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 2417, in resolve
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/dvha-0.8.1-py3.6.egg/dvha/main.py", line 29, in <module>
    from dvha.models.database_editor import DatabaseEditorFrame
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/dvha-0.8.1-py3.6.egg/dvha/models/database_editor.py", line 22, in <module>
    from dvha.models.roi_map import RemapROIFrame
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/dvha-0.8.1-py3.6.egg/dvha/models/roi_map.py", line 23, in <module>
    from dvha.models.plot import PlotROIMap
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/dvha-0.8.1-py3.6.egg/dvha/models/plot.py", line 30, in <module>
    from dvha.tools.stats import MultiVariableRegression, get_control_limits
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/dvha-0.8.1-py3.6.egg/dvha/tools/stats.py", line 19, in <module>
    from regressors import stats as regressors_stats
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/regressors-0.0.3-py3.6.egg/regressors/stats.py", line 11, in <module>
    import pandas as pd
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/__init__.py", line 124, in <module>
    from pandas.core.computation.api import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/eval.py", line 14, in <module>
    from pandas.core.computation.engines import _engines
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/Users/ninja/PycharmProjects/DVH-Analytics/venv2/lib/python3.6/site-packages/pandas-1.0.3-py3.6-macosx-10.6-intel.egg/pandas/core/computation/ops.py", line 15, in <module>
    import pandas.core.common as com
AttributeError: module 'pandas' has no attribute 'core'
```

**Comment by cutright** [comment]
DVHA v0.8.1 includes the requirement of pandas <=0.25.3

**Comment by cutright** [comment]
`pandas == 1.0.3, 1.0.4` seem to have no issues on MSW7, could be a macOS issue?
