### ISSUE TITLE
MANIFEST.in missing TG263_Nomenclature_Worksheet_20170815.csv

### ISSUE THREAD

**Issue by SotiriStathakis** [cutright/DVH-Analytics#91]
Hi @cutright 

I have installed DVHanalytics on a mac and I am getting the errors below. Can you please let me know what I am missing?
Thanks

=====================
ERROR: Unhandled exception: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dvha/main.py", line 1196, in OnInit
    self.frame = DVHAMainFrame(None, wx.ID_ANY, "")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dvha/main.py", line 145, in __init__
    self.roi_map = DatabaseROIs()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dvha/tools/roi_name_manager.py", line 226, in __init__
    self.import_from_file()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dvha/tools/roi_name_manager.py", line 243, in import_from_file
    self.import_physician_roi_maps()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dvha/tools/roi_name_manager.py", line 259, in import_physician_roi_maps
    self.import_physician_roi_map(abs_file_path, physician)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dvha/tools/roi_name_manager.py", line 273, in import_physician_roi_map
    for line in document:
  File "/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2982: invalid start byte

OnInit returned false, exiting...

**Comment by cutright** [comment]
I'm not 100% sure, but I seem to recall python 3.8 having a conflict with something.  I think something changed with the framework (Tk/Tcl).

Can you try again with python 3.7?

**Comment by SotiriStathakis** [comment]
Hi,

Thanks for the advice.
I looked closely to the error. We figured out that the TG263xxxx.csv file was missing from the site specific libraries. I copied it and everything worked.

I am not sure why that happened.

I will keep you posted if anything else comes up

Best Regards,

Sotiri Stathakis, PhD, DABR


On Aug 31, 2020, at 4:30 PM, Dan Cutright <notifications@github.com> wrote:

﻿

I'm not 100% sure, but I seem to recall python 3.8 having a conflict with something. I think something changed with the framework (Tk/Tcl).

Can you try again with python 3.7?

**Comment by cutright** [comment]
Oh man, I'm really sorry about that.  [MANIFEST.in](https://github.com/cutright/DVH-Analytics/blob/master/MANIFEST.in) needs to be updated to include the file.  DVHA users using the executable (rather than from source) didn't have this issues since a different file determines what is included.

I'll push a fix tonight.  Thanks.

**Comment by cutright** [comment]
Issue was reproduced running `dvha` after  a `pip install dvha`

Issue resolved as of `v0.8.4.post1`
